---
title: "DelayedArray Tweaks"
output: html_document
---

<style>
pre {
  overflow-x: auto;
}
pre code {
  word-wrap: normal;
  white-space: pre;
}
</style>

```{r global_options, echo = FALSE, include = FALSE}
options(width = 150)
```

This time we want to make sure we're using the modified versions of both **rhdf5** and **DelayedArray**.
 
```{r, installBranch, results = 'hide', message = FALSE, warning = FALSE}
if(packageVersion('rhdf5') == "2.23.1") {
    BiocInstaller::biocLite('grimbough/rhdf5', ref = "91f2e40", suppressUpdates = TRUE, ask = FALSE)
}
if(packageVersion('DelayedArray') == "0.5.6") {
    BiocInstaller::biocLite('Bioconductor/DelayedArray', suppressUpdates = TRUE, ask = FALSE)
    BiocInstaller::biocLite("Bioconductor/HDF5Array", suppressUpdates = TRUE, ask = FALSE)
}
```

```{r, load-libs, message=FALSE}
library(TENxBrainData)
library(microbenchmark)
options(DelayedArray.block.size=2e9)
```

```{r, load-data, message=FALSE}
tenx <- TENxBrainData()
tenx.sub <- tenx[,1:13000]
```

```{r, save-results}
systime <- system.time(res4 <- colSums(counts(tenx.sub)))
save(res4, file = "res4.rda")
systime
```

```{r, step4-run-benchmark}
packageVersion('rhdf5')
packageVersion('DelayedArray')

bm4 <- microbenchmark(colSums(counts(tenx.sub)), 
                      times = 5L, unit = "s",
                      control = list(order = "block", warmup = 0))
bm4 <- rbind(data.frame(expr = "", time = as.numeric(systime[3]) * 1e9), bm4)

bm4$expr <- "rhdf5 &\nDelayedArray"
save(bm4, file = "bm4.rda")
bm4
```

```{r, sessionInfo}
devtools::session_info(c("HDF5Array", "DelayedArray"))
```