---
title: "Summarising"
author: "Mike Smith"
output: html_document
---

## Summarising the results
 
```{r, load-benchmarks, results = 'hide', message = FALSE, warning = FALSE}
library(ggplot2)
library(microbenchmark)

f1 <- list.files("/media/Storage/Work/TENxBenchmarking", 
                 pattern = "bm[0-9a-z]*.rda", full.names = TRUE)
sapply(X = f1, load, envir = .GlobalEnv)
```

```{r, combine-benchmarks}
bm <- rbind(bm1,bm1a,bm2,bm3,bm3a,bm4,bm5)
bm
bm$expr <- factor(bm$expr, levels = c("naive", "block_size", "uncompressed", "rhdf5", "DelayedArray", "DelayedArray+\nrhdf5", "DelayedArray+\nrhdf5+\nuncompressed", "in_mem"))
bm$cmp <- ifelse(grepl(x = bm$expr, "uncompressed"),"uncompressed", "compressed")
```

```{r, plotting, out.width = "100%"}
ggplot(bm, aes(x = expr, y = time / 1e9), fill = cmp) + 
    geom_boxplot(fill = "deepskyblue3") + 
    ylab("time (secs)") + 
    xlab("setting") +
    theme(axis.text=element_text(size=6))
```

```{r, plotting2, out.width = "100%"}
bm.first <- bm[seq(1,nrow(bm),by = 5),]
ggplot(bm.first, aes(x = expr, y = time / 1e9, fill = cmp)) + 
    geom_bar(stat = 'identity') + 
    ylab("time (secs)") + 
    xlab("setting") +
    theme(axis.text=element_text(size=6))
```

```{r, loadResults}
f2 <- list.files("/media/Storage/Work/TENxBenchmarking", 
                 pattern = "res[0-9a-z]*.rda", full.names = TRUE)
sapply(X = f2, load, envir = .GlobalEnv)
```

```{r, test-identical}
sapply(list(res1, res2, res3, res3a, res4, res5), FUN = all.equal, current = res1, check.names = FALSE)
```

```{r, sessionInfo}
sessionInfo()
```