---
title: "scater, beachmat, and uncompressed data"
output: html_document
---

<style>
pre {
  overflow-x: auto;
}
pre code {
  word-wrap: normal;
  white-space: pre;
}
</style>

```{r global_options, echo = FALSE, include = FALSE}
options(width = 150)
```

```{r, setup, echo=FALSE, message=FALSE}
if(packageVersion('scater') < "1.7.3") {
    devtools::install_github(repo = "davismcc/scater", quiet = TRUE, force = TRUE)
}
```

```{r, load-libs, message=FALSE}
library(TENxBrainData)
library(microbenchmark)
library(scater)
tenx <- TENxBrainData()
options(DelayedArray.block.size=2e9)
```

Create a new *SingleCellExperiment* object using the uncompressed HDF5Array as the counts table.

```{r, load-data}
h5.uncmp <- HDF5Array(file = '/tmpdata/msmith/tenx_uncompressed.h5', 
                      name = "counts")
tenx.uncmp <- SingleCellExperiment(
    list(counts = h5.uncmp), rowData = rowData(tenx), colData = colData(tenx)
)
tenx.sub.uncmp <- tenx.uncmp[,1:13000]
```

```{r, save-results}
systime <- system.time(res7 <- scater:::.colSums(counts(tenx.sub.uncmp)))
save(res7, file = "res7.rda")
systime
```

```{r, step7-run-benchmark}
bm7 <- microbenchmark(scater:::.colSums(counts(tenx.sub.uncmp)),
                      times = 5L, unit = "s",
                      control = list(order = "block", warmup = 0))
bm7 <- rbind(data.frame(expr = "", time = as.numeric(systime[3]) * 1e9), bm7)

bm7$expr <- "scater2"
save(bm7, file = "bm7.rda")
bm7
```

```{r, sessionInfo}
devtools::session_info(c("HDF5Array", "DelayedArray"))
```