---
output: 
    html_document: default
---

```{r, exhub, echo = FALSE, message = FALSE}
if(packageVersion('rhdf5') != "2.23.0") {
    BiocInstaller::biocLite('rhdf5', suppressUpdates = TRUE, ask = FALSE)
}
if(packageVersion('DelayedArray') != "0.5.1") {
    BiocInstaller::biocLite('DelayedArray', suppressUpdates = TRUE, ask = FALSE)
}

library(ExperimentHub)
setExperimentHubOption("cache", "/tmpdata/msmith/ExperimentHub/")
```
    
## Loading the TenX brain data
    
```{r, load-data, message=FALSE}
library(TENxBrainData)
library(pryr)
library(microbenchmark)
tenx <- TENxBrainData()
dim(tenx)
```

```{r, select-subset}
tenx.sub <- tenx[,1:13000]
#tenx.sub <- tenx
system.time(tenx.inmem <- as.matrix(counts(tenx.sub)))
object_size(tenx.sub)
object_size(tenx.inmem)
```

## Calculating column sums

```{r, colSums}
bm1 <- microbenchmark(colSums(counts(tenx.sub)),
                colSums(tenx.inmem), 
               times = 10L, unit = "s",
               control = list(order = "block", warmup = 2))
bm1$expr <- rep(c("naive", "in_mem"), each = 10)
save(bm1, file = "/g/huber/users/msmith/hdf5_benchmarking/bm1.rda")
bm1
```

## Increasing the DelayedArray block size

First we'll look at the current block size.  Then we'll adjust it to use 2Gb.

```{r, increase-block-size}
options()$DelayedArray.block.size
options(DelayedArray.block.size=2e9)
```

Now we'll calculate the column sums again.  Hopefully the time will decrease now there is less time spend loading data into memory.

```{r, bigger-block}
packageVersion('rhdf5')
packageVersion('DelayedArray')

bm1a <- microbenchmark(colSums(counts(tenx.sub)), 
                       times = 10L, unit = "s",
                       control = list(order = "block", warmup = 2))
bm1a$expr <- "block_size"
save(bm1a, file = "/g/huber/users/msmith/hdf5_benchmarking/bm1a.rda")
bm1a
```



