---
title: "Uncompressed HDF5 + Improvements"
output: html_document
---

```{r, setup, echo=FALSE, message=FALSE}
if(packageVersion('rhdf5') == "2.23.0") {
    devtools::install_github(repo = "grimbough/rhdf5", ref = "5e1f0be", quiet = TRUE, force = TRUE)
}
if(packageVersion('DelayedArray') == "0.5.1") {
    devtools::install_github(repo = "grimbough/DelayedArray", ref = "b2374e7",  quiet = TRUE, force = TRUE)
}

library(ExperimentHub)
setExperimentHubOption("cache", "/tmpdata/msmith/ExperimentHub/")
```

```{r, load-data, message=FALSE}
library(TENxBrainData)
library(microbenchmark)
options(DelayedArray.block.size=2e9)
```


```{r, uncompressed-tweaks}
tenx.uncmp <- HDF5Array(file = '/tmpdata/msmith/tenx_uncompressed.h5', 
                            name = "counts")
tenx.sub.uncmp <- tenx.uncmp[,1:13000]

bm5 <- microbenchmark(colSums(tenx.sub.uncmp),
                      times = 10L, unit = "s",
                      control = list(order = "block", warmup = 2))
bm5$expr <- "DelayedArray+\nrhdf5+\nuncompressed"
save(bm5, file = "/g/huber/users/msmith/hdf5_benchmarking/bm5.rda")
bm5
```

```{r, faster-disk, eval = FALSE}
tenx.uncmp2 <- HDF5Array(file = '/tmpdata/msmith/tenx_uncompressed.h5', 
                            name = "counts")
tenx.sub.uncmp2 <- tenx.uncmp2[,1:13000]

bm5a <- microbenchmark(colSums(tenx.sub.uncmp2),
                       times = 10L, unit = "s",
                       control = list(order = "block", warmup = 2))
bm5a$expr <- "local_disk"
save(bm5a, file = "/g/huber/users/msmith/hdf5_benchmarking/bm5a.rda")
bm5a
```
